/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "business_consolidation-detail": () => import("@/views/business/consolidation-detail/[pk].vue"),
  "business_consolidation-edite": () => import("@/views/business/consolidation-edite/[pk].vue"),
  business_consolidation: () => import("@/views/business/consolidation/index.vue"),
  "business_shipment-edit": () => import("@/views/business/shipment-edit/[pk].vue"),
  "business_shipment-new": () => import("@/views/business/shipment-new/index.vue"),
  business_shipment: () => import("@/views/business/shipment/index.vue"),
  home: () => import("@/views/home/index.vue"),
  maintain_airlines: () => import("@/views/maintain/airlines/index.vue"),
  maintain_bank: () => import("@/views/maintain/bank/index.vue"),
  "maintain_carrier-contract": () => import("@/views/maintain/carrier-contract/index.vue"),
  "maintain_charge-code": () => import("@/views/maintain/charge-code/index.vue"),
  "maintain_charter-flight": () => import("@/views/maintain/charter-flight/index.vue"),
  maintain_commodities: () => import("@/views/maintain/commodities/index.vue"),
  "maintain_consignee-contract": () => import("@/views/maintain/consignee-contract/index.vue"),
  maintain_containers: () => import("@/views/maintain/containers/index.vue"),
  maintain_currency: () => import("@/views/maintain/currency/index.vue"),
  maintain_equipment: () => import("@/views/maintain/equipment/index.vue"),
  "maintain_exchange-rate": () => import("@/views/maintain/exchange-rate/index.vue"),
  "maintain_international-zone": () => import("@/views/maintain/international-zone/index.vue"),
  "maintain_mawb-stock": () => import("@/views/maintain/mawb-stock/index.vue"),
  "maintain_organization-detail": () => import("@/views/maintain/organization-detail/index.vue"),
  "maintain_organization-edit": () => import("@/views/maintain/organization-edit/[pk].vue"),
  "maintain_organization-new": () => import("@/views/maintain/organization-new/index.vue"),
  maintain_organization: () => import("@/views/maintain/organization/index.vue"),
  "maintain_package-types": () => import("@/views/maintain/package-types/index.vue"),
  "maintain_port-code": () => import("@/views/maintain/port-code/index.vue"),
  "maintain_service-level": () => import("@/views/maintain/service-level/index.vue"),
  "maintain_shipping-lines": () => import("@/views/maintain/shipping-lines/index.vue"),
  "maintain_shipping-schedule": () => import("@/views/maintain/shipping-schedule/index.vue"),
  maintain_vessel: () => import("@/views/maintain/vessel/index.vue"),
  maintain_warehouse: () => import("@/views/maintain/warehouse/index.vue"),
  "settlement_billing-detail": () => import("@/views/settlement/billing-detail/index.vue"),
  "settlement_payable-transactions": () => import("@/views/settlement/payable-transactions/index.vue"),
  "settlement_receivable-transactions": () => import("@/views/settlement/receivable-transactions/index.vue"),
  "settlement_writeoff-create": () => import("@/views/settlement/writeoff-create/index.vue"),
  "settlement_writeoff-detail": () => import("@/views/settlement/writeoff-detail/index.vue"),
  "settlement_writeoff-edit": () => import("@/views/settlement/writeoff-edit/index.vue"),
  settlement_writeoff: () => import("@/views/settlement/writeoff/index.vue"),
  system_branch: () => import("@/views/system/branch/index.vue"),
  system_company: () => import("@/views/system/company/index.vue"),
  system_group: () => import("@/views/system/group/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
};
