/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteRecordRaw, RouteComponent } from 'vue-router';
import type { ElegantConstRoute } from '@elegant-router/vue';
import type { RouteMap, RouteKey, RoutePath } from '@elegant-router/types';

/**
 * transform elegant const routes to vue routes
 * @param routes elegant const routes
 * @param layouts layout components
 * @param views view components
 */
export function transformElegantRoutesToVueRoutes(
  routes: ElegantConstRoute[],
  layouts: Record<string, RouteComponent | (() => Promise<RouteComponent>)>,
  views: Record<string, RouteComponent | (() => Promise<RouteComponent>)>
) {
  return routes.flatMap(route => transformElegantRouteToVueRoute(route, layouts, views));
}

/**
 * transform elegant route to vue route
 * @param route elegant const route
 * @param layouts layout components
 * @param views view components
 */
function transformElegantRouteToVueRoute(
  route: ElegantConstRoute,
  layouts: Record<string, RouteComponent | (() => Promise<RouteComponent>)>,
  views: Record<string, RouteComponent | (() => Promise<RouteComponent>)>
) {
  const LAYOUT_PREFIX = 'layout.';
  const VIEW_PREFIX = 'view.';
  const ROUTE_DEGREE_SPLITTER = '_';
  const FIRST_LEVEL_ROUTE_COMPONENT_SPLIT = '$';

  function isLayout(component: string) {
    return component.startsWith(LAYOUT_PREFIX);
  }

  function getLayoutName(component: string) {
    const layout = component.replace(LAYOUT_PREFIX, '');

    if(!layouts[layout]) {
      throw new Error(`Layout component "${layout}" not found`);
    }

    return layout;
  }

  function isView(component: string) {
    return component.startsWith(VIEW_PREFIX);
  }

  function getViewName(component: string) {
    const view = component.replace(VIEW_PREFIX, '');

    if(!views[view]) {
      throw new Error(`View component "${view}" not found`);
    }

    return view;
  }

  function isFirstLevelRoute(item: ElegantConstRoute) {
    return !item.name.includes(ROUTE_DEGREE_SPLITTER);
  }

  function isSingleLevelRoute(item: ElegantConstRoute) {
    return isFirstLevelRoute(item) && !item.children?.length;
  }

  function getSingleLevelRouteComponent(component: string) {
    const [layout, view] = component.split(FIRST_LEVEL_ROUTE_COMPONENT_SPLIT);

    return {
      layout: getLayoutName(layout),
      view: getViewName(view)
    };
  }

  const vueRoutes: RouteRecordRaw[] = [];

  // add props: true to route
  if (route.path.includes(':') && !route.props) {
    route.props = true;
  }

  const { name, path, component, children, ...rest } = route;

  const vueRoute = { name, path, ...rest } as RouteRecordRaw;

  try {
    if (component) {
      if (isSingleLevelRoute(route)) {
        const { layout, view } = getSingleLevelRouteComponent(component);

        const singleLevelRoute: RouteRecordRaw = {
          path,
          component: layouts[layout],
          meta: {
            title: route.meta?.title || ''
          },
          children: [
            {
              name,
              path: '',
              component: views[view],
              ...rest
            } as RouteRecordRaw
          ]
        };

        return [singleLevelRoute];
      }

      if (isLayout(component)) {
        const layoutName = getLayoutName(component);

        vueRoute.component = layouts[layoutName];
      }

      if (isView(component)) {
        const viewName = getViewName(component);

        vueRoute.component = views[viewName];
      }

    }
  } catch (error: any) {
    console.error(`Error transforming route "${route.name}": ${error.toString()}`);
    return [];
  }

  // add redirect to child
  if (children?.length && !vueRoute.redirect) {
    vueRoute.redirect = {
      name: children[0].name
    };
  }

  if (children?.length) {
    const childRoutes = children.flatMap(child => transformElegantRouteToVueRoute(child, layouts, views));

    if(isFirstLevelRoute(route)) {
      vueRoute.children = childRoutes;
    } else {
      vueRoutes.push(...childRoutes);
    }
  }

  vueRoutes.unshift(vueRoute);

  return vueRoutes;
}

/**
 * map of route name and route path
 */
const routeMap: RouteMap = {
  "root": "/",
  "not-found": "/:pathMatch(.*)*",
  "403": "/403",
  "404": "/404",
  "500": "/500",
  "business": "/business",
  "business_consolidation": "/business/consolidation",
  "business_consolidation-detail": "/business/consolidation-detail/:pk",
  "business_consolidation-edite": "/business/consolidation-edite/:pk",
  "business_shipment": "/business/shipment",
  "business_shipment-edit": "/business/shipment-edit/:pk",
  "business_shipment-new": "/business/shipment-new",
  "home": "/home",
  "iframe-page": "/iframe-page/:url",
  "login": "/login/:module(pwd-login)?",
  "maintain": "/maintain",
  "maintain_airlines": "/maintain/airlines",
  "maintain_bank": "/maintain/bank",
  "maintain_carrier-contract": "/maintain/carrier-contract",
  "maintain_charge-code": "/maintain/charge-code",
  "maintain_charter-flight": "/maintain/charter-flight",
  "maintain_commodities": "/maintain/commodities",
  "maintain_consignee-contract": "/maintain/consignee-contract",
  "maintain_containers": "/maintain/containers",
  "maintain_currency": "/maintain/currency",
  "maintain_equipment": "/maintain/equipment",
  "maintain_exchange-rate": "/maintain/exchange-rate",
  "maintain_international-zone": "/maintain/international-zone",
  "maintain_mawb-stock": "/maintain/mawb-stock",
  "maintain_organization": "/maintain/organization",
  "maintain_organization-detail": "/maintain/organization-detail",
  "maintain_organization-edit": "/maintain/organization-edit/:pk",
  "maintain_organization-new": "/maintain/organization-new",
  "maintain_package-types": "/maintain/package-types",
  "maintain_port-code": "/maintain/port-code",
  "maintain_service-level": "/maintain/service-level",
  "maintain_shipping-lines": "/maintain/shipping-lines",
  "maintain_shipping-schedule": "/maintain/shipping-schedule",
  "maintain_vessel": "/maintain/vessel",
  "maintain_warehouse": "/maintain/warehouse",
  "settlement": "/settlement",
  "settlement_billing-detail": "/settlement/billing-detail",
  "settlement_payable-transactions": "/settlement/payable-transactions",
  "settlement_receivable-transactions": "/settlement/receivable-transactions",
  "settlement_writeoff": "/settlement/writeoff",
  "settlement_writeoff-create": "/settlement/writeoff-create",
  "settlement_writeoff-detail": "/settlement/writeoff-detail",
  "settlement_writeoff-edit": "/settlement/writeoff-edit",
  "system": "/system",
  "system_branch": "/system/branch",
  "system_company": "/system/company",
  "system_group": "/system/group",
  "system_user": "/system/user"
};

/**
 * get route path by route name
 * @param name route name
 */
export function getRoutePath<T extends RouteKey>(name: T) {
  return routeMap[name];
}

/**
 * get route name by route path
 * @param path route path
 */
export function getRouteName(path: RoutePath) {
  const routeEntries = Object.entries(routeMap) as [RouteKey, RoutePath][];

  const routeName: RouteKey | null = routeEntries.find(([, routePath]) => routePath === path)?.[0] || null;

  return routeName;
}
